### PR TITLE
Adding support for discovering source information to tests

### PR DESCRIPTION
**Pull request by rynowak**
/cc @davidfowl

### CODE REVIEW

**Comment by davidfowl** [comment]
- Fix the formatting of the com interfaces.
- Shouldn't the method to create test service, create all of them? (the sinks etc)
- I did some testing hardcoding the line number and source path and couldn't get "run this test" (ctrl+r, ctrl+t) to work

**Comment by rynowak** [comment]
>Fix the formatting of the com interfaces.
Fixed

> Shouldn't the method to create test service, create all of them? (the sinks etc).
I'll give this a try. should be good cleanup.

BTW you probably noticed, I wrote this guy in anticipation of adding logging.

> I did some testing hardcoding the line number and source path and couldn't get "run this test" (ctrl+r, ctrl+t) to work.

You need a private build of the runner which consumes this new service. I haven't had any issues with ctrl+r, ctrl+t on my box.

The only problem I've run into thus far is that DIA isn't giving line info for some of the MVC tests. I've debugged it far enough at this point to see that we do have a symbol for the method, and the symbol resolver found it, but then DIA doesn't give back any line number info.

**Comment by rynowak** [comment]
@davidfowl updated.

An easy way to tell if it's working btw is to look at the test explorer window. Click on something and it will show a line number or not. Also this makes grouping by project work!

**Comment by davidfowl** [comment]
:shipit:

**Pull request closed without merging**
