### PR TITLE
Add ExceptionAssert.ThrowsArgumentNull

### PR DESCRIPTION
**Pull request by GrabYourPitchforks**
Makes it useful to test methods which perform null checks on their parameters.

/cc @BrennanConroy

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@GrabYourPitchforks__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Levi Broderick). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla2.msopentech.com.
    </p>

TTYL, MSOTBOT;

**Comment by BrennanConroy** [comment]
Add ThrowsArgumentNullAsync like some of the others? Or is there no good reason for that

**Comment by GrabYourPitchforks** [comment]
Argument exceptions should always be thrown synchronously, even for async methods. There's no benefit to an async version.

**Comment by BrennanConroy** [comment]
I thought the async versions were just for writing async tests and being able to await the check

**Comment by GrabYourPitchforks** [comment]
Nope - they're for unwrapping exceptions from Task instances. This should never happen for argument nulls.

**Comment by BrennanConroy** [comment]
:shipit:

**Comment by davidfowl** [comment]
Assuming we never merged this in @BrennanConroy ?

**Comment by BrennanConroy** [comment]
We didn't

**Comment by Eilon** [comment]
@BrennanConroy if it's safe to add, no harm in adding it. Please confirm, and rebase and merge.

**Comment by BrennanConroy** [comment]
029e716780f180b552d6b1b28072223ad53f37ef

**Pull request closed without merging**
