### PR TITLE
Change Microsoft.AspNet.Tooling to use the same `xunit` as everything else

### PR DESCRIPTION
**Pull request by dougbu**
- adjust to core interface changes
- likely some expectations still are not met

### CODE REVIEW

**Comment by dougbu** [comment]
fixes #75; will update the commit description before pushing...

**Comment by dougbu** [comment]
ah, @NTaylorMullen has already signed off on the underlying branch. getting this in now.

**Comment by dougbu** [comment]
commit d479387

**Comment by NTaylorMullen** [comment]
:shipit:

**Pull request merged**
