### PR TITLE
Add conditional attributes for Docker testing

### PR DESCRIPTION
**Pull request by natemcmaster**
Create test attributes to make it easier to write tests that will only run when certain command lines tools are available, or will only run when inside a Docker container.

Part of https://github.com/aspnet/Testing/issues/277, but not a complete solution. A complete fix will need to coordinate with koreBuild to replicate the dotnet runtime and SDK versions into test containers.

### CODE REVIEW

**Comment by pakrym** [comment]
Wouldn't this prevent us from noticing misconfigured agents that are not running tests? Why is it better to skip then to fail?

**Comment by natemcmaster** [comment]
IMO skip is better here, but that's not the full story. The rest of the design I have in mind is to add a KoreBuild target that creates an image and re-launches tests inside the docker container. _That_ layer can be configured to fail if docker is not available.

**Comment by pakrym** [comment]
What if test needs to configure logging container itself?

**Comment by natemcmaster** [comment]
Can you provide an example of where we need that? That is probably out-of-scope for this PR. As I said, this is only part of #277

**Comment by pakrym** [comment]
For example DataProtection warning message tests, one needs to have volume mounted folder to check that warning is not displayed, another - non volume mounted to check that the warning is produced.

**Comment by natemcmaster** [comment]
Currently thinking a docker-compose.yml file will be the best way to configure this. DataProtection would add a docker-compose.yml file. KoreBuild would be improved to understand how to launch and run a test project using this file.

**Comment by natemcmaster** [comment]
Discussed in person. @pakrym are you ok with this now?

**Comment by pakrym** [comment]
Does this mean we would run all unit test in docker even non docker ones?

**Comment by natemcmaster** [comment]
This PR is not addressing that. This only means that I can specify "this test should only run inside docker". I'm not yet attempting to solve the problem of how we bootstrap the test project into the default build cycle, build containers, manage versions of stuff in the image, etc. I'm going to punt that one until we have more pressing needs, and until we've triaged #277

**Pull request merged**
