### PR TITLE
Cross compile TestHost

### PR DESCRIPTION
**Pull request by pranavkm**
Partial work towards fixing #174

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @rynowak

**Comment by rynowak** [comment]
What do you expect this to **do** on net451? This requires a bunch of dnx-isms

**Comment by davidfowl** [comment]
Yes this doesn;t make sense on net451

**Comment by pranavkm** [comment]
Ok. I'll rollback `Microsoft.Aspnet.Testing` and other libraries that depend on it to cross compile on dnx451 and dnxcore50.

**Pull request closed without merging**
